config/routes.rb
Rails.application.routes.draw do
  get 'home/ceremony'

  get 'home/rsvp'

  root 'home#index'

  get 'home/index'

  get 'rsvp' => 'home#rsvp', as: :rsvp
  get 'ceremony' => 'home#ceremony', as: :ceremony

  post 'send_rsvp', to: 'home#send_rsvp', as: :rsvp_forms

  namespace :admin do
    root 'home#index'
    get 'home/index'
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/rsvp_form.rb
class RsvpForm < MailForm::Base
  attribute :name, :validate => true
  attribute :email, :validate => /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i
  attribute :attending
  attribute :message
  #attribute :file, :attachment => true

  # attribute :message, :validate => true
  #attribute :nickname,  :captcha  => true

  # Declare the e-mail headers. It accepts anything the mail method
  # in ActionMailer accepts.
  def headers
    subject = 'RSVP de ' + self.name
    {
        :subject => %("#{subject}"),
        :to => "nielson@bitmine.com.br, lnplins@gmail.com",
        :from => %("[RSVP] #{name}" <#{email}>)
    }
  end
end

app/controllers/admin/home_controller.rb
class Admin::HomeController < ApplicationController
  layout 'admin'

  def index
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # protect_from_forgery with: :exception
  protect_from_forgery with: :null_session

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def rsvp
    @rsvp_form = RsvpForm.new
  end

  def send_rsvp
    all_error_required = params[:all_error_required]
    all_input_id = params[:all_input_id]

    if not all_error_required.nil?
      output = {type: 'text', text: params[:all_error_required]}
    elsif not all_input_id.nil?


      @rsvp_form = RsvpForm.new
      @rsvp_form.name = params[:inputname]
      @rsvp_form.email = params[:inputemail]
      @rsvp_form.attending = params['events-checkbox_label'] + params['events-checkbox']
      @rsvp_form.message = params[:inputmessage]

      if @rsvp_form.deliver
        output = {type: 'success', text: 'Confirmação enviada. Agradecemos muito!'}
      else
        output = {type: 'error', text: 'Houve um problema ao enviar sua confirmação. Desculpe-nos.'}
      end

    end

    respond_to do |format|
      format.json { render json: output }
    end
  end

  def ceremony
  end
end

app/helpers/admin/home_helper.rb
module Admin::HomeHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/admin/home/index.html.erb
<h1>Admin::Home#index</h1>
<p>Find me in app/views/admin/home/index.html.erb</p>

app/views/home/ceremony.html.erb
<!-- MAIN SLIDER -->
<section id="main-slider" class="fixed-height">

  <!-- MAIN SLIDER TITLE OUTTER WRAPPER -->
  <div class="slide-title-outter-wrapper">

    <!-- MAIN SLIDER TITLE INNER WRAPPER -->
    <div class="slide-title-inner-wrapper">

      <!-- TITLE 1  -->
      <div class="slide-title align-bottom">

        <div class="container">
          <div class="row">
            <div class="col-md-offset-2 col-md-8">

              <div class="page-title">
                <h1>CERIMÔNIA & RECEPÇÃO</h1>

                <div class="heart-divider">
                  <span class="white-line-double-size"></span>
                </div>

              </div>

            </div>
          </div>
        </div>

      </div>

    </div><!-- END of MAIN SLIDER TITLE INNER WRAPPER -->

  </div> <!-- END of MAIN SLIDER TITLE OUTTER WRAPPER -->

  <!-- MAIN SLIDER IMAGES -->
  <div class="slides">
    <!-- SLIDE IMAGE -->
    <div data-stellar-ratio="0.5" class="slide-image change-to-d-mobile" style="background-image:url(<%= asset_path('d.jpg') %>);">
    </div>

    <div class="slide-overlay" style="opacity:0.2"></div>
  </div>  <!-- END of MAIN SLIDER IMAGES -->

</section><!-- ENF of MAIN SLIDER -->

<!--CONTENT SECTION-->
<section id="content">

  <!-- CONTAINER -->
  <div class="container">

    <!-- ROW-1 -->
    <div class="row">
      <br /><br />
      <div class="col-md-offset-1 col-md-5">

        <div class="white-box-content-wrapper animation fadeInLeft">
          <h3>CERIMÔNIA RELIGIOSA</h3>
          <span>Igreja Mosteiro de São Bento<br/><br/></span>
          <p>
            Av. Gen. Osório - Centro, 58010-780
          </p>
          <div id="map-ceremony" style="height:550px; width:100%;"></div>
        </div>

      </div>

      <div class="col-md-5">

        <div class="white-box-content-wrapper animation fadeInLeft delay1">
          <h3>RECEPÇÃO</h3>
          <span>&nbsp;<br/><br/></span>
          <p>
            Av. Gov. Argemiro de Figueiredo, 1170 - Bessa
          </p>
          <div id="map-party" style="height:550px; width:100%;"></div>
        </div>

      </div>

    </div><!--END of ROW-1-->


  </div> <!-- END of CONTAINER -->

</section> <!--END of CONTENT SECTION-->

app/views/home/index.html.erb
<!-- MAIN SLIDER -->
<section id="main-slider" class="flexslider fullscreen">

  <!-- MAIN SLIDER TITLE OUTTER WRAPPER -->
  <div class="slide-title-outter-wrapper">

    <!-- MAIN SLIDER TITLE INNER WRAPPER -->
    <div class="slide-title-inner-wrapper">

      <!-- TITLE -->
      <div class="slide-title align-bottom">

        <div class="container">
          <div class="row">
            <div class="col-md-offset-3 col-md-6 animation delay1 fadeInUp">
              <div id="save-the-date">
                <div id="date">01<span class="pink-dot">.</span>10<span class="pink-dot">.</span>16</div>
              </div>
            </div>
          </div>
        </div>

      </div>

    </div><!-- END of MAIN SLIDER TITLE INNER WRAPPER -->

  </div> <!-- END of MAIN SLIDER TITLE OUTTER WRAPPER -->

  <!-- MAIN SLIDER IMAGES -->

  <ul class="slides">


    <li>
      <!-- SLIDE IMAGE -->
      <div data-stellar-ratio="0.5" class="slide-image change-to-a-mobile" style="background-image:url(<%= asset_path('a.jpg') %>);">
      </div>

      <!-- SLIDE OVERLAY -->
      <div class="slide-overlay" style="opacity:0.2"></div>
    </li>

    <li>
      <!-- SLIDE IMAGE -->
      <div data-stellar-ratio="0.5" class="slide-image change-to-b-mobile" style="background-image:url(<%= asset_path('b.jpg') %>);">
      </div>

      <!-- SLIDE OVERLAY -->
      <div class="slide-overlay" style="opacity:0.2"></div>
    </li>

    <li>
      <!-- SLIDE IMAGE -->
      <div data-stellar-ratio="0.5" class="slide-image change-to-c-mobile" style="background-image:url(<%= asset_path('c.jpg') %>);">
      </div>

      <!-- SLIDE OVERLAY -->
      <div class="slide-overlay" style="opacity:0.2"></div>
    </li>

    <li>
      <!-- SLIDE IMAGE -->
      <div data-stellar-ratio="0.5" class="slide-image change-to-d-mobile" style="background-image:url(<%= asset_path('d.jpg') %>);">
      </div>

      <!-- SLIDE OVERLAY -->
      <div class="slide-overlay" style="opacity:0.2"></div>
    </li>

    <li>
      <!-- SLIDE IMAGE -->
      <div data-stellar-ratio="0.5" class="slide-image change-to-e-mobile" style="background-image:url(<%= asset_path('e.jpg') %>);">
      </div>

      <!-- SLIDE OVERLAY -->
      <div class="slide-overlay" style="opacity:0.2"></div>
    </li>

    <li>
      <!-- SLIDE IMAGE -->
      <div data-stellar-ratio="0.5" class="slide-image change-to-f-mobile" style="background-image:url(<%= asset_path('f.jpg') %>);">
      </div>

      <!-- SLIDE OVERLAY -->
      <div class="slide-overlay" style="opacity:0.2"></div>
    </li>

    <li>
      <!-- SLIDE IMAGE -->
      <div data-stellar-ratio="0.5" class="slide-image change-to-g-mobile" style="background-image:url(<%= asset_path('g.jpg') %>);">
      </div>

      <!-- SLIDE OVERLAY -->
      <div class="slide-overlay" style="opacity:0.2"></div>
    </li>

    <li>
      <!-- SLIDE IMAGE -->
      <div data-stellar-ratio="0.5" class="slide-image change-to-h-mobile" style="background-image:url(<%= asset_path('h.jpg') %>);">
      </div>

      <!-- SLIDE OVERLAY -->
      <div class="slide-overlay" style="opacity:0.2"></div>
    </li>

    <li>
      <!-- SLIDE IMAGE -->
      <div data-stellar-ratio="0.5" class="slide-image change-to-i-mobile" style="background-image:url(<%= asset_path('i.jpg') %>);">
      </div>

      <!-- SLIDE OVERLAY -->
      <div class="slide-overlay" style="opacity:0.2"></div>
    </li>

    <li>
      <!-- SLIDE IMAGE -->
      <div data-stellar-ratio="0.5" class="slide-image change-to-j-mobile" style="background-image:url(<%= asset_path('j.jpg') %>);">
      </div>

      <!-- SLIDE OVERLAY -->
      <div class="slide-overlay" style="opacity:0.2"></div>
    </li>

    <li>
      <!-- SLIDE IMAGE -->
      <div data-stellar-ratio="0.5" class="slide-image change-to-l-mobile" style="background-image:url(<%= asset_path('l.jpg') %>);">
      </div>

      <!-- SLIDE OVERLAY -->
      <div class="slide-overlay" style="opacity:0.2"></div>
    </li>

  </ul><!-- END of MAIN SLIDER IMAGES -->

</section><!-- ENF of MAIN SLIDER -->


<!--CONTENT SECTION-->
<section id="content">

  <!-- LOCATION & COUNTDOWN SECTION -->
  <section id="location-countdown">
    <div class="image-divider auto-height" data-stellar-background-ratio="0.5">

      <div class="divider-overlay"></div>

      <!-- Use Center Middle Alignment to align middle the content for fixed-height parallax
      <div class="alignment">
        <div class="v-align center-middle"> -->

      <div class="container">
        <div class="row">
          <div class="col-md-offset-1 col-md-10 text-center">

            <div class="animation fadeInUp">
              <div id="counting-down">
                <div id="counting"></div>
                <div id="down">Faltam</div>
              </div>
            </div>

            <div class="heart-divider animation fadeInUp">
              <span class="white-line-double-size"></span>
            </div>

            <div id="countdown" class="simple-countdown animation fadeInUp"></div>

          </div>
        </div>
      </div>

      <!--</div>
    </div>-->

    </div>
  </section>


  <!-- GIFT LISTS SECTION -->
  <section id="gift-list-section">

    <div class="container">

      <!-- ROW-1 -->
      <div class="row">

        <!-- SECTION TITLE -->
        <div class="col-md-12 text-center">

          <div class="section-title animation fadeInUp">
            <h2>
              LISTAS DE PRESENTES
            </h2>

            <div class="heart-divider">
              <span class="grey-line-double-size"></span>
            </div>

            <h3>Listas Virtuais</h3>

          </div>
        </div>
      </div> <!-- END of ROW-1 -->


      <!-- ROW-2 -->
      <div class="row">

        <div class="col-md-offset-1 col-md-10">

          <div class="container-fluid">
            <div class="row">

              <!-- ITEM-1 -->
              <div class="wedding-item col-md-offset-2 col-md-4 animation fadeIn">

                <!--PHOTO-ITEM-->
                <div class="photo-item">

                  <!--PHOTO-->
                  <%= image_tag 'icasei.png', class: "hover-animation image-zoom-in" %>

                  <!--PHOTO OVERLAY-->
                  <div class="layer wh95 hidden-black-overlay hover-animation fade-in">
                  </div><!--END of PHOTO OVERLAY-->

                  <div class="layer wh95 border-photo-caption fade-out">
                  </div><!--END of PHOTO CAPTION-->

                  <!--ICON LINK-->
                  <div class="layer wh100 hidden-link hover-animation delay1 fade-in">
                    <div class="alignment">
                      <div class="v-align center-middle">

                        <a href="https://sites.icasei.com.br/laluehumberto/pt_br/store/index/9?id_loja=1" class="de-button outline small" target="_blank">
                          LISTA DE PRESENTES
                        </a>

                      </div>
                    </div>
                  </div><!--END of ICON LINK-->

                </div><!--END of PHOTO-ITEM-->

                <!-- TITLE & EXCERPT -->
                <div class="title-excerpt">
                  <h3 class="text-center">
                    <a href="https://sites.icasei.com.br/laluehumberto/pt_br/store/index/9?id_loja=1" target="_blank">iCASEI</a>
                  </h3>
                </div>
                <!-- END of TITLE & EXCERPT -->

              </div><!-- END of ITEM-1 -->


              <!-- ITEM-2 -->
              <div class="wedding-item  col-md-4 animation delay1 fadeIn">

                <!--PHOTO-ITEM-->
                <div class="photo-item">

                  <!--PHOTO-->
                  <%= image_tag 'tania-bulhoes.png', class: "hover-animation image-zoom-in" %>

                  <!--PHOTO OVERLAY-->
                  <div class="layer wh95 hidden-black-overlay hover-animation fade-in">
                  </div><!--END of PHOTO OVERLAY-->

                  <div class="layer wh95 border-photo-caption fade-out">

                  </div><!--END of PHOTO CAPTION-->

                  <!--ICON LINK-->
                  <div class="layer wh100 hidden-link hover-animation delay1 fade-in">
                    <div class="alignment">
                      <div class="v-align center-middle">

                        <a href="http://www.taniabulhoes.com.br/list/laluehumberto" class="de-button outline small" target="_blank">
                          LISTA DE PRESENTES
                        </a>

                      </div>
                    </div>
                  </div><!--END of ICON LINK-->

                </div><!--END of PHOTO-ITEM-->

                <!-- TITLE & EXCERPT -->
                <div class="title-excerpt">
                  <h3 class="text-center">
                    <a href="http://www.taniabulhoes.com.br/list/laluehumberto" target="_blank">TANIA BULHÕES</a></h3>
                </div>
                <!-- END of TITLE & EXCERPT -->

              </div><!-- END of ITEM-2 -->


            </div>


          </div>

        </div>
      </div><!-- END of ROW-2 -->

      <!-- ROW-3 -->
      <div class="row">

        <!-- SECTION TITLE -->
        <div class="col-md-12 text-center">

          <div class="section-title animation fadeInUp">

            <div class="heart-divider">
              <span class="grey-line-double-size"></span>
            </div>

            <h3>Listas Físicas</h3>

          </div>
        </div>
      </div> <!-- END of ROW-3 -->

      <!-- ROW-4 -->
      <div class="row">

        <div class="col-md-offset-1 col-md-10">

          <div class="container-fluid">
            <div class="row">

              <!-- ITEM-1 -->
              <div class="wedding-item col-md-3 animation fadeIn">

                <!-- TITLE & EXCERPT -->
                <div class="title-excerpt">
                  <h3 class="text-center"><a href="https://goo.gl/maps/WLknogJZR3H2" target="_blank">APRIMORE ELETRO</a>
                  </h3>
                  <p>
                    <a href="https://goo.gl/maps/WLknogJZR3H2" target="_blank">Av. Gen. Edson Ramalho, 372, Manaíra<br/>João
                      Pessoa, PB<br/>58038-100</a></p>
                  <p>(83) 3031-6552</p>
                </div>
                <!-- END of TITLE & EXCERPT -->

              </div><!-- END of ITEM-1 -->


              <!-- ITEM-2 -->
              <div class="wedding-item col-md-3 animation delay1 fadeIn">


                <!-- TITLE & EXCERPT -->
                <div class="title-excerpt">
                  <h3 class="text-center">
                    <a href="https://goo.gl/maps/97e69NbDbMF2" target="_blank">BAZAART</a></h3>
                  <p>
                    <a href="https://goo.gl/maps/97e69NbDbMF2" target="_blank">Av. Gen. Edson Ramalho, 804, Manaíra<br/>João
                      Pessoa, PB<br/>58038-100</a></p>
                  <p>(83) 3247-5676</p>
                </div>
                <!-- END of TITLE & EXCERPT -->

              </div><!-- END of ITEM-2 -->


              <!-- ITEM-3 -->
              <div class="wedding-item col-md-3 animation delay2 fadeIn">

                <!-- TITLE & EXCERPT -->
                <div class="title-excerpt">
                  <h3 class="text-center">
                    <a href="https://goo.gl/maps/iVkjzdeSfmp" target="_blank">CASA CHANG</a></h3>
                  <p>
                    <a href="https://goo.gl/maps/iVkjzdeSfmp" target="_blank">Av. Gen. Edson Ramalho, 1061, Manaíra<br/>João
                      Pessoa, PB<br/>58038-100</a></p>
                  <p>(83) 3214-9400</p>
                </div>
                <!-- END of TITLE & EXCERPT -->

              </div> <!-- END of ITEM-3 -->

              <!-- ITEM-4 -->
              <div class="wedding-item col-md-3 animation delay3 fadeIn">

                <!-- TITLE & EXCERPT -->
                <div class="title-excerpt">
                  <h3 class="text-center"><a href="https://goo.gl/maps/f4CJzhvBVsy">PERFORMATO</a></h3>
                  <p><a href="https://goo.gl/maps/f4CJzhvBVsy" target="_blank">Av. Pres. Epitácio Pessoa,
                    Tambauzinho<br/>João Pessoa, PB<br/>58042-020</a></p>
                  <p>(83) 3214-7733</p>
                </div>
                <!-- END of TITLE & EXCERPT -->

              </div> <!-- END of ITEM-4 -->

            </div>


          </div>

        </div>
      </div><!-- END of ROW-4 -->

    </div><!-- END of CONTAINER -->

  </section>


  <!-- RSVP SECTION -->
  <section id="rsvp">

    <div class="container">
      <div class="row">

        <!-- SECTION TITLE -->
        <div class="col-md-12 text-center ">

          <div class="section-title animation fadeInUp">
            <div class="heart-divider">
              <i class="de-icon-circle pink-heart"></i>
              <i class="de-icon-circle grey-heart"></i>
            </div>

            <h2>
              CONFIRMAÇÃO DE PRESENÇA
            </h2>

            <%= link_to 'RSVP', rsvp_path, class: "de-button medium animation fadeInUp" %>
          </div>

        </div>

      </div>
    </div>

  </section>


</section>

app/views/home/rsvp.html.erb
<div id="map-ceremony" style="display:none;"></div>
<div id="map-party" style="display:none;"></div>

<!-- MAIN SLIDER -->
<section id="main-slider" class="fixed-height">

  <!-- MAIN SLIDER TITLE OUTTER WRAPPER -->
  <div class="slide-title-outter-wrapper">

    <!-- MAIN SLIDER TITLE INNER WRAPPER -->
    <div class="slide-title-inner-wrapper">

      <!-- TITLE 1  -->
      <div class="slide-title align-bottom">

        <div class="container">
          <div class="row">
            <div class="col-md-offset-2 col-md-8">

              <div class="page-title">
                <h1>RSVP</h1>

                <div class="heart-divider">
                  <span class="white-line-double-size"></span>
                </div>

              </div>

            </div>
          </div>
        </div>

      </div>

    </div><!-- END of MAIN SLIDER TITLE INNER WRAPPER -->

  </div> <!-- END of MAIN SLIDER TITLE OUTTER WRAPPER -->

  <!-- MAIN SLIDER IMAGES -->
  <div class="slides">
    <!-- SLIDE IMAGE -->
    <div data-stellar-ratio="0.5" class="slide-image change-to-i2-mobile" style="background-image:url(<%= asset_path('i2.jpg') %>);">
    </div>

    <div class="slide-overlay" style="opacity:0.2"></div>
  </div>  <!-- END of MAIN SLIDER IMAGES -->

</section><!-- ENF of MAIN SLIDER -->


<!--CONTENT SECTION-->
<section id="content">

  <!-- ICON -->
  <div class="icon-title">
    <div class="de-icon circle light large-size aligncenter">
      <i class="de-icon-mail-2"></i>
    </div>
  </div>

  <!-- CONTAINER -->
  <div class="container">


    <%= simple_form_for @rsvp_form, html: {class: 'contact-form forms', id: 'rsvpform'} do |f| %>
        <%= hidden_field_tag :authenticity_token, form_authenticity_token %>

        <!--TEXT SECTION-->
        <br/><br/><br/>
        <div class="row">
          <div id="message" class="col-md-12 message">
            <!-- Show Message -->
          </div>
        </div>
        <div class="row">
          <div class="col-md-6">
            <div class="form-group">
              <label for="inputname">NOME *</label>
              <input type="text" class="form-control ajax-input" id="inputname" placeholder="" data-required="Name Required" data-output-label="Output Name">
            </div>
            <div class="form-group">
              <label for="inputemail">E-MAIL *</label>
              <input type="email" class="form-control ajax-input" id="inputemail" placeholder="" data-required="Email Required" data-output-label="Output Email">
            </div>
            <div class="form-group">
              <label>CONFIRMO PRESENÇA *</label>
              <div id="events-checkbox" class="ajax-input ajax-checkbox" data-required="Please Select Events" data-output-label="Confirmo presença: ">
                <div class="btn-group" data-toggle="buttons">
                  <label class="btn btn-primary custom-option-icon">
                    <input type="checkbox" id="wedding-ceremony" value="Cerimônia Religiosa"> Cerimônia Religiosa
                  </label>
                  <label class="btn btn-primary custom-option-icon">
                    <input type="checkbox" id="wedding-party" value="Recepção"> Recepção
                  </label>
                </div>
              </div>
            </div>


          </div>
          <div class="col-md-6">

            <div class="form-group">
              <label for="inputmessage">DEIXA UMA MENSAGEM</label>
              <textarea id="inputmessage" class="form-control ajax-input" rows="15" data-output-label="Output Message"></textarea>
            </div>
          </div>
        </div><!--END of TEXT SECTION-->

        <div class="row">
          <div class="col-md-12 text-center">
            <div class="form-group">
              <input type="submit" id="submitButton" name="submitButton" class="button medium reverse" value="ENVIAR">
            </div>
          </div>
        </div>

  <% end %>

    <br/><br/><br/>

  </div><!-- END of CONTAINER -->

</section> <!--END of CONTENT SECTION-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta content="width=device-width, initial-scale=1.0" name="viewport">
  <meta name="description" content="">
  <meta name="author" content="www.dethemes.com">
  <title>Lalu &amp; Humberto</title>

  <link rel="icon" href="favicon.ico">

  <%= stylesheet_link_tag 'application', media: 'all' %>

  <!-- Icon -->
  <link rel="stylesheet" href="css/fonts/fontello/css/fontello.css" type="text/css" media="screen"/>
  <!-- Font -->
  <link href='http://fonts.googleapis.com/css?family=Oswald' rel='stylesheet' type='text/css'>
  <link href='http://fonts.googleapis.com/css?family=Arvo:400,700' rel='stylesheet' type='text/css'>
  <link href='http://fonts.googleapis.com/css?family=Pacifico' rel='stylesheet' type='text/css'>

</head>

<body>
<!--PRELOADER-->
<div id="preloader">

  <div class="alignment">
    <div class="v-align center-middle">

      <!-- LEFT HEART -->
      <div class="heart-animation">
        <i class="de-icon-circle"></i>
      </div>

      <!-- RIGHT HEART -->
      <div class="heart-animation-reverse">
        <i class="de-icon-circle"></i>
      </div>

    </div>
  </div>

</div> <!--END of PRELOADER-->


<!-- NAVIGATION -->
<header id="nav-header">
  <nav id="nav-bar" class="top-bar fluid-width transparent nav-center sticky-nav animation fadeInDown">

    <div id="nav-wrapper">

      <!-- LOGO -->
      <div class="logo-wrapper">
        <!-- CSS LOGO -->
        <%= link_to(image_tag('monograma.png'), root_path) %>
        <!-- IMG LOGO
          <a href="index.html">
          <div class="img-logo">
            <img src="images/slide1.jpg">
          </div>
          </a>
          -->
      </div>
      <!-- END of LOGO -->

      <div id="mobile-nav">
        <i class="de-icon-menu"></i>
      </div>

      <ul id="nav-menu" class="nav-smooth-scroll">
        <li class="first-child">
          <%= link_to 'INÍCIO', root_path %>
        </li>
        <li>
          <a href="/ceremony">CERIMÔNIA RELIGIOSA</a>
        </li>
        <li>
          <a href="/ceremony">RECEPÇÃO</a>
        </li>


        <li class="smooth-scroll first-child split-margin">
          <a href="/#gift-list-section">LISTAS</a>
        </li>

        <li>
          <%= link_to 'RSVP', rsvp_path %>
        </li>
        <li>
          <a href="https://www.instagram.com/explore/tags/casamentolaluehumberto/" target="_blank">#casamentolaluehumberto</a>
        </li>
      </ul>

      <div class="clearboth"></div>

    </div>

  </nav>
</header> <!-- END of NAVIGATION -->




<%= yield %>




<!-- FOOTER SECTION -->
<footer id="application_footer">
  <div class="image-divider fixed-height change-to-j-peb-mobile" style="background-image:url(<%= asset_path('j-peb.jpg') %>);" data-stellar-background-ratio="0.5">

    <div class="divider-overlay"></div>

    <!-- Use Center Middle Alignment to align middle the content for fixed-height parallax -->
    <div class="alignment">
      <div class="v-align center-middle">

        <div class="container">
          <div class="row">
            <div class="col-md-12">

              <div id="footer-couple-name" class="animation delay1 fadeInUp">
                LARISSA & HUMBERTO
              </div>

            </div>
          </div>
        </div>

      </div>
    </div>

  </div>

  <div id="map-canvas" style="display: none;"></div>
</footer>


<!-- - - - - - - - - - - - Bottom Footer - - - - - - - - - - - - -->

<div class="bottom-footer">
  <div class="container">
    <div class="row">
      <div class="col-sm-6">
        <div class="copyright">
          Copyright ©
          <script>document.write(new Date().getFullYear())</script>
          .
          Larissa & Humberto. Todos os direitos reservados
        </div>
      </div>

      <div class="col-sm-3 col-sm-offset-3">
        <div class="developed">
          Desenvolvido por
          <%= link_to(image_tag('logo-bitmine-100.png', class: 'logo-bitmine', width: '70'), 'http://bitmine.com.br', target: '_blank') %>
        </div>
      </div>
    </div><!--/ .row-->
  </div><!--/ .container-->
</div><!--/ .bottom-footer-->

<!-- - - - - - - - - - - end Bottom Footer - - - - - - - - - - - -->

<!-- Google Map -->
<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCqPMgHdlC6gRO0ianhqPmL-dHa3aOUpXM" type="text/javascript"></script>

<%= javascript_include_tag 'application' %>
<%= javascript_include_tag 'countdown/jquery.countdown-custom-label' %>

</body>
</html>